### ISSUE TITLE
glib error, skype wrapper doesnt work

### ISSUE THREAD

**Issue by guiodic** [sagetarian/skype-wrapper#1]
GLib-GIO-ERROR **: Settings schema 'apps.skype-wrapper' is not installed

aborting...
Applet closed
API crash detected
Restarting skype-wrapper

..........
# gsettings list-schemas | grep app

org.gnome.desktop.default-applications.office.tasks
apps.gnome-mplayer.preferences
org.gnome.desktop.default-applications.office
org.gnome.desktop.default-applications.office.calendar
org.gnome.desktop.default-applications.terminal
org.gnome.desktop.a11y.applications
apps.gecko-mediaplayer.preferences
apps.indicators.weather
org.gnome.desktop.default-applications

but I see it in dconf-editor and there is the file applets.skype-wrapper-py.gschema.xml in /usr/share/glib-2.0/schemas

**Comment by guiodic** [comment]
#sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
/usr/share/glib-2.0/schemas/applets.skype-wrapper-py.gschema.xml: Errore alla riga 33 carattere 1: invalid name 'show-outgoing-filetransfer-progress': maximum length is 32.  This entire file has been ignored.

**Comment by sagetarian** [comment]
thanks for this :) i had no idea that their was a maximum length for these things, it works fine on my system .. i have adjusted it .. try it out in the downloads section .. version 5.1 is the latest.. let me know if this is fixed

**Comment by guiodic** [comment]
ok, now it is better but still it doesnt work (I tjink for a different reason).

Starting skype-wrapper
INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process

**Comment by sagetarian** [comment]
Thanks for you patience .. 

What version of Ubuntu are you running?
What version of python-skype are you running?

Skype is refusing to send a "yeah you can connect" callback .. have you been requested to allow SKype4Py to access skype yet?

**Comment by guiodic** [comment]
I use natty and python-skype 1.0.32

skype-wrapper doesnt ask me the autorization. While skype-indicator does.

**Comment by sagetarian** [comment]
thats the problem .. python-skype 1.0.32 is really buggy .. remove it and install this one

http://ftp.us.debian.org/debian/pool/contrib/s/skype4py/python-skype_1.0.31.0-2_all.deb

**Comment by guiodic** [comment]
a bit better but...

INFO: Attaching skype-wrapper to Skype process
INFO: Attached complete
INFO: Checking unread messages
INFO: Checking online status changing users
INFO: Checking online presence
INFO: Checking file transfers
INFO: Check if Skype instance is running
ERROR: Skype instance is now defunct, exiting badly
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/pymodules/python2.7/Skype4Py/API/posix_x11.py", line 225, in run
  File "/usr/lib/python2.7/threading.py", line 404, in wait
  File "/usr/lib/python2.7/threading.py", line 237, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Applet closed

actually skype is not closed but become offline

**Comment by guiodic** [comment]
ah ok, it was really a defuncted skype, i killed it now it is good

**Comment by guiodic** [comment]
closed ;)
