### ISSUE TITLE
[Feature]: Ability to skip notifications from certain contacts

### ISSUE THREAD

**Issue by tverdohleb** [sagetarian/skype-wrapper#15]
Is there an ability to suppress notifications from chats with disabled alerts (/alertsoff)? If it is impossible, just give ability to make some "blacklist" of chats I want to ignore.

**Comment by sagetarian** [comment]
good feature :)

**Comment by tverdohleb** [comment]
I've made some investigations on the Skype4Py and found that there are [AlertString](http://skype4py.sourceforge.net/doc/html/Skype4Py.chat.Chat-class.html#AlertString) property of Chat class and this this may help. I can try to integrate it myself, but unfortunately i don't figured out how to install skype-wrapper from source:(

**Comment by sagetarian** [comment]
Ah legendary .. problem is that this is only for chat notifications not for online / file transfer statuses .. i'll implement this and a gsetting called the "list-of-silence" .. sounds better than blacklist ;)

**Comment by sagetarian** [comment]
unfortuneatly the AlertString doesn't work in Skype4Py .. i'm going to investigate further .. but i've implemented the list-of-silence .. just list all the usernames in dconf-editor .. get the latest at 

https://github.com/sagetarian/skype-wrapper/downloads

**Comment by sagetarian** [comment]
oh and if you wanna try this from source .. i just run edit and run <code>/usr/share/skype-wrapper/indicator-applet-skype.py</code>. The skype-wrapper.py doesn't do anything except manage running the applet, if the applet is already running it will bring focus the already running one :) fyi

**Comment by sagetarian** [comment]
AlertString is a fail on python-skype .. Opening a bug report for that and marking this feature as complete

Here's the bug

https://github.com/sagetarian/skype-wrapper/issues/18
