### ISSUE TITLE
[Bug]: No notifications after installation with custom skype command

### ISSUE THREAD

**Issue by bilderbuchi** [sagetarian/skype-wrapper#17]
Hi!

After setting up skype-wrapper and adding it to autostart it seems to work correctly. I confirmed the api popup and can see this in skype options. skype starts on boot, goes online, generally works, is integrated into the messaging menu (so I can close it to the m.m., and restore it from there), I can quit, everything. skype-wrapper is running. 
Only thing: I get no Ubuntu-notifications. I got some "is online" notifications once, but never since (even after several reboots). All notifications are activated in dconf-editor. Incoming messages etc trigger the skype notifications (so there appears a small window at the lower left), but no ubuntu ones (upper right).

Also, I can't change skype status with the buttons in the m.m. (I seem to recall that that is supposed to work?)

Only special things I can think of: I'm on Ubuntu 11.10 64bit (but didn't have to force the installation of skype-wrapper), and I'm using a custom dbpath launch option to point to my skype profile in a custom location.

**Comment by sagetarian** [comment]
hmmm .. kill indicator-skype and run /usr/share/skype-wrapper/indicator-applet-skype.py in terminal and see if any WARNING comes up .. it sounds like the notiifications are silently failing

**Comment by sagetarian** [comment]
im going to add logging to text file in the next release to help me debug without asking you to go through too much hassle , so thanks for the patience

**Comment by sagetarian** [comment]
regarding setting status.. see if you fit this description

https://github.com/sagetarian/skype-wrapper/issues/12

**Comment by bilderbuchi** [comment]
If everything is running, I kill indicator-skype, and start it in the terminal (skype is still running), notifications start to work, but I get two skype icons in the mess. menu. and skype has ~20 and indicator-skype ~14% cpu load, even after notifications stop appearing.

If I kill/quit all 3 processes, and start the terminal command, skype start without working notifications, and terminal output is

$ /usr/share/skype-wrapper/indicator-applet-skype.py
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
INFO: Initializing Skype API
Corrupt JPEG data: 291 extraneous bytes before marker 0xd9
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process

**Comment by bilderbuchi** [comment]
@setting status: I got empathy running at the same time, using a google account. Is that what is meant by telepathy account? Empathy changes status according to m.m., in any case.

**Comment by sagetarian** [comment]
im wondering why corrup jpeg data is there .. :P i dont do any jpeg stuff before running .. cool, i'll have to sort out that error logging to get a better debug of your system ..

**Comment by bilderbuchi** [comment]
avatar pictures maybe?

**Comment by bilderbuchi** [comment]
OK, so if I disable the custom command I have, quit everything, and then start skype-wrapper, skype starts, minimizes after a while, then notifications start working, but I get 2 skype symbols in UMM.
Also, upon reboot, one time I got multiple (6 or so) skype instances started. I couldn't shut them all down.
Also, even if I get just one instance, I'm also hit by the high CPU bug.
Btw, even if I uncheck notify-on-initialise, I get a load of "bla is online" notifications in the beginning (but that's really minor)
This is with skype-wrapper 0ubuntu5-3

log goes something like this.
python-skype: 1.0.31.0-2
python-imaging: 1.1.7-3ubuntu1
Python-2.6, 2.7
WARNING: Checking unread messages failed: Skype command timeout
WARNING: Checking unread messages failed: Skype command timeout
WARNING: Checking online status changing users failed
WARNING: Checking online presence failed
WARNING: Checking file transfers failed (Skype attach timeout)
WARNING: Checking unread messages failed: Skype attach timeout
WARNING: Checking online status changing users failed
WARNING: Checking online status changing users failed
WARNING: Checking online presence failed
WARNING: Skype instance has terminated, exiting
WARNING: Checking unread messages failed: Skype command timeout
WARNING: Checking unread messages failed: Skype command timeout
WARNING: Checking unread messages failed: Skype command timeout
WARNING: Checking unread messages failed: Skype command timeout
WARNING: Checking unread messages failed: Skype command timeout
WARNING: Checking unread messages failed: Skype command timeout
WARNING: Checking unread messages failed: Skype command timeout
WARNING: Checking online status changing users failed
...

**Comment by sagetarian** [comment]
awesome .. the latest should sort out the issues here

the latest version is on its way to your PPA .. if you're impatient then download here

https://github.com/sagetarian/skype-wrapper/blob/master/skype-wrapper_0ubuntu5-4.3_all.deb?raw=true

let me know if this fixes it

**Comment by bilderbuchi** [comment]
Yes, notifications seem to be fixed now. still got 2 skype icons in UMM, but I'll ignore that for now. Will observe further...

**Comment by bilderbuchi** [comment]
ok, i can confirm that notifications work now. closing this. will open a separate bug for the 2 skype icons.
