### ISSUE TITLE
[Packaging] Make changelog available to package manager

### ISSUE THREAD

**Issue by bilderbuchi** [sagetarian/skype-wrapper#21]
A minor point, really low priority since many other official packages also don't do this:
In Synaptic, you can click the "Get changelog" button, which should fetch the changelog for a package. When I do this for skype-wrapper, I get:

This change is not coming from a source that supports changelogs.
Failed to fetch the changelog for skype-wrapper
URI was: http://ppa.launchpad.net/pool/main/s/skype-wrapper/skype-wrapper_0ubuntu5-3_all.changelog

I figure there's just a file which has to be created on packaging to make this work.

**Comment by sagetarian** [comment]
strange .. i can reproduce this, but i do have a changelog, obviously the PPA isn't building it .. even though you need a .changes file to upload to the repo :P

**Comment by grissir** [comment]
ppas don't include changelogs for the package manager, only the standart ubuntu repositories support this ;(

you can look up changelogs here https://launchpad.net/~skype-wrapper/+archive/ppa/+packages

**Comment by bilderbuchi** [comment]
Ah, interesting, didn't know that. I'll close this, then.

**Comment by sagetarian** [comment]
can be honest and say .. that sucks :P

**Comment by bilderbuchi** [comment]
and the relevant bug report where you can pitch in: https://bugs.launchpad.net/launchpad/+bug/253119
