### ISSUE TITLE
[BUG]: Error while installing skype-wrapper 0.5.3 on ubuntu maverick

### ISSUE THREAD

**Issue by thangnc** [sagetarian/skype-wrapper#24]
thangnc@thangnc-Inspiron-N5010:~/Downloads$ sudo dpkg --force-all -i skype-wrapper_0ubuntu5-3.7_all.deb 
Selecting previously deselected package skype-wrapper.
(Reading database ... 157911 files and directories currently installed.)
Unpacking skype-wrapper (from skype-wrapper_0ubuntu5-3.7_all.deb) ...
Setting up skype-wrapper (0ubuntu5-3.7) ...WARNING: compile error while trying to byte-compile /usr/share/skype-wrapper/indicator-applet-skype.py: SyntaxError: ('invalid syntax', ('/usr/share/skype-wrapper/indicator-applet-skype.py', 293, 18, '        "user256", \n'))

Im running Ubuntu Maverick. The version 0.1, 0.2 & 0.3 installed successfully on my laptop. But no notifications when skype got events.

**Comment by sagetarian** [comment]
Maverick is not supported yet .. we use very unity specific calls .. but i should change this ;) also the syntax error is for a valid python line .. what version of python are you using so i can create a portable piece

**Comment by thangnc** [comment]
Thks sagetarian. I edited some code from file indicator-applet-skype.py. Just removed unity callers & comment content in code block userProfile. It now running fine on Ubuntu 10.10. Hope the new branch for Maverick :-)

**Comment by sagetarian** [comment]
Do you see notifications in the UMM? and Notify OSD messages? :) this is interesting

**Comment by thangnc** [comment]
Yeah. I see all notifications. Notify OSD is very good. Except no avatars in notifications. Maybe the reason is i commented the code block userProfile :-)

**Comment by sagetarian** [comment]
yeah thats why .. try changing that userProfile block to instead of curly brackets , use square ..

i.e 

userprofile = []
userprofile.append(''user256')

etc ..

or 

userprofile = {
   0:'user256',
   // etc
}

or 

userprofile = {
   'user256' : true,
   // etc
}

**Comment by sagetarian** [comment]
Awesome mate .. you are going down for letting Maverick use skype-wrapper :D i'll just do a check for if unity is installed, if not, don't run any unity related functions .. this will help with gnome-shell integration

**Comment by thangnc** [comment]
I will try tonight.Will report A.S.A.P

**Comment by thangnc** [comment]
I tried with this block while running skype-wrapper from terminal
userfiles = {
    "user256":true, 
        "user1024":true, 
        "user4096":true, 
        "user16384":true, 
        "user32768":true, 
        "user65536":true,
        "profile256":true, 
        "profile1024":true, 
        "profile4096":true, 
        "profile16384":true, 
        "profile32768":true
}
and i got this warning from command line
WARNING: Checking online status changing users failed (global name 'true' is not defined)

Also, notifications not work in this case. I also tried this block
userfiles = {
        0:"user256", 
        1:"user1024", 
        2:"user4096", 
        3:"user16384", 
        4:"user32768", 
        5:"user65536",
        6:"profile256", 
        7:"profile1024", 
        8:"profile4096", 
        9:"profile16384", 
        10:"profile32768"
}
Got notifications online/offline but still no avatar icons and no notification while checking unread message
WARNING: Checking unread messages failed: global name 'username' is not defined

# 

Awesome, it's running well with below block 
userfiles = []
    userfiles.append("user256")
    userfiles.append("user1024")
    userfiles.append("user4096")
    userfiles.append("user16384")
    userfiles.append("user32768")
    userfiles.append("user65536")
    userfiles.append("profile256")
    userfiles.append("profile1024")
    userfiles.append("profile4096")
    userfiles.append("profile16384")
    userfiles.append("profile32768")

Got all notifications, avatars...

**Comment by sagetarian** [comment]
awesome .. however i just created a fix for you... its in https://github.com/downloads/sagetarian/skype-wrapper/skype-wrapper_0ubuntu5-4.1_all.deb

if it doesnt work, i'll use your block of code .. this version also checks if unity is installed (shouldnt be in maverick) .. if its not installed then it wont do any unity calls .. so you dont need to patch .. let me know if this works Out The Box for you, so i can take a step closer to knocking off maverick as a supported OS

**Comment by thangnc** [comment]
Updated your patch. No notifications for messages. Run skype-wrapper from terminal. And got this exception

INFO: Updating Indicator
INFO: Found avatar for phamlenguyen
INFO: Wrote avatar to file /home/thangnc/.thumbnails/normal/skype-wrapper-phamlenguyen.jpg
indicator-applet-skype.py:226: Warning: g_value_get_string: assertion `G_VALUE_HOLDS_STRING (value)' failed
  if bitmapVersion != self.indicators[conversation.indicator_name].get_property("icon"):
INFO: Updating Indicator
INFO: Found avatar for phamlenguyen
INFO: Wrote avatar to file /home/thangnc/.thumbnails/normal/skype-wrapper-phamlenguyen.jpg

It seems to be always updated avatar whenever received message?

**Comment by sagetarian** [comment]
have no fear :) ive just installed maverick on my laptop, will sort it out .. as for saving avatars everytime you receive a message .. this is to make sure you have the latest avatars for those users :) the performance bottleneck is quite small because sleep the process every 500ms, this gives the kernel time to prioritise other processes over it

**Comment by thangnc** [comment]
Oops. After install 0.5.4 and got no Notify OSD for unread message. I did a rollback 0.5.3. But still got same warning in 0.5.4 :-(

**Comment by sagetarian** [comment]
hmmm. have you installed 0.5.4.1?

**Comment by thangnc** [comment]
yes, already. No notify OSD for unread message.

**Comment by sagetarian** [comment]
can you switch the lines

if bitmapVersion != self.indicators[conversation.indicator_name].get_property("icon"):
&nbsp;&nbsp;&nbsp;&nbsp;self.indicators[conversation.indicator_name].set_property("icon", str(user_avatar.get_bitmap_version()))

to 

self.indicators[conversation.indicator_name].set_property("icon", str(user_avatar.get_bitmap_version()))

that might do the trick

**Comment by thangnc** [comment]
Changed it. Still got no Notify OSD. Received warning from terminal
WARNING: Checking unread messages failed: global name 'username' is not defined

**Comment by thangnc** [comment]
Just changed the lines
<code>
 if not fullname:
     fullname = username
</code>
to 

<code>
if not fullname:
     fullname = conversation.display_name
</code>
Everything is great :-) Got notifications, notify OSD, click on Me menu and jump into conversation window :D

**Comment by sagetarian** [comment]
awesome :) great stuff man .. i'll patch your work right in

**Comment by thangnc** [comment]
There is still lil bug in version 0.5.4.1. If user doesn't install skype-wrapper yet, and he/she installs it in the first time. The skype's permission for Skype4Py will open many dialogs if he/she doesn't click Yes quickly in the first dialog. And after many dialogs appear, we can't close dialogs even click Yes already. I still don't understand this bug. The version 0.5.3.3 doesn't have same bug.

**Comment by sagetarian** [comment]
cool, the latest should sort out all issues here

the latest version is on its way to your PPA .. if you're impatient then download here

https://github.com/sagetarian/skype-wrapper/blob/master/skype-wrapper_0ubuntu5-4.3_all.deb?raw=true

let me know if this fixes it

**Comment by thangnc** [comment]
The latest deb file still get same bug as i reported which concern to unitylauncher. Don't understand. I can see you put if helper.haveUnity() already. Hmm
