### ISSUE TITLE
[Feature Request]: Display name should be full name in contact list

### ISSUE THREAD

**Issue by thangnc** [sagetarian/skype-wrapper#28]
Currently, the display names in notifications are Skype's contact full name, not alias which we rename in our contact list. They should be alias in our contact list. Then we can know exactly who they are. I don't know Skype4Py already support yet?

**Comment by thangnc** [comment]
Please change <code>skypefriends.FullName</code> to <code>skypefriends.DisplayName</code>. This will fetch display name (alias which we renamed) in contact list instead of full name of friends

**Comment by sagetarian** [comment]
Will be fixed in the next release
