### ISSUE TITLE
[Feature Request]: Reduce notifications OSD while initializing contact list

### ISSUE THREAD

**Issue by thangnc** [sagetarian/skype-wrapper#31]
Can we make our application same as Empathy or Pidgin notifications? While initializing contact list right after signing in Skype, no need to send notification OSD concern to friend's  status (online/offline). We only need to check unread messages only. After the application ready, this is the time to check & send notification OSD concern to checking status.

**Comment by grissir** [comment]
you can cahnge settings with the dconf editor

**Comment by thangnc** [comment]
What do u mean? The configuration setting for checking online/offline affects for all time. I mean the time after signing in Skype successfully and initializing contact list. After initialization finished, we still need to check online status. Currently, the notify OSD for unread messages has to wait for notify OSD for checking online status finish. Too long and no need. These notify OSD appear after you checked unread message.So strange. Please review Empathy/Pidgin notify OSD.

**Comment by bilderbuchi** [comment]
he means the option "notify-on-initializing" - Skype likes to let you know who’s online as soon as you sign in, setting this to false stops skype-wrapper from notifying whos online during startup

**Comment by thangnc** [comment]
I tried that option. Unchecked it but skype-wrapper still send notify OSD for status online of contact list. Just checked this code to call init online users
<code>
def initOnlineUserList(self) :
    if self.skype.Friends:
        for friend in self.skype.Friends:
            if not friend.Handle in self.usersonline:
                if friend.OnlineStatus != "OFFLINE":
                    self.usersonline[friend.Handle] = friend.FullName
</code>

I dont think this code prevent sending notify OSD. Becoz the function checkOnlineUsers(self) always be called right after skype-wrapper init.

**Comment by grissir** [comment]
ok I see the function is useless

**Comment by sagetarian** [comment]
that function adds all online contacts to the list during start up, it doesn't notify Ubuntu about them being online .. if the setting to notify on startup is enabled, that list is fed to the notification list, otherwise it isn't .. the option works in my version, can you test the latest build in the downloads section of the repo .. keeping the repo as a development version and PPA for as stable release as possible

**Comment by sagetarian** [comment]
closing until its reproduced :)
