### ISSUE TITLE
.desktop file having Name=Skype  is confusing

### ISSUE THREAD

**Issue by felagund** [sagetarian/skype-wrapper#32]
skype-wrapper has a .desktop file as follows:

[Desktop Entry]
Name=Skype
Comment=Skype Internet Telephony
Exec=skype-wrapper
Icon=skype
NoDisplay=true
Terminal=false
Type=Application
Encoding=UTF-8

Name and Icon is the same as Skype.
 Now I understand why this change came about (afaik it was not like this in earlier versions ,but it is confusing . When I search for skype in unity, which one actually appears? Currently, there is no way to tell. I tried dragging the skype icon from dash to to Startup applications (launched via session-indicator) and skype executalbe got added, not skype-wrapper as I would like to.

**Comment by sagetarian** [comment]
Fix to be released
