### ISSUE TITLE
[Bug] 2 Skype icons in Messaging Menu

### ISSUE THREAD

**Issue by bilderbuchi** [sagetarian/skype-wrapper#33]
Using 0ubuntu5-4.3~oneiric2 (with a custom command, if that's relevant), I get 2 skype icons in UMM. On boot, skype-wrapper starts skype, the interface appears for a couple seconds, then minimizes itself.
Initially, only the upper one of both icons has a white triangle on the left side, but both open the skype interface on click.

Also, the icons are the original, blue ones, and not monochrome, I don't know if that's still intended or not.
## Log file (level 0)

INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
INFO: Attached complete
INFO: Checking unread messages
WARNING: Checking unread messages failed: Skype command timeout
INFO: Checking online status changing users
INFO: Checking online presence
INFO: Checking file transfers
WARNING: Checking file transfers failed (Skype command timeout)
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
etc...

**Comment by david-barbion** [comment]
I remember having this type of problem too (happen only once), but I can't remember how to reproduce...
It was on release 0.4.

**Comment by bilderbuchi** [comment]
I still see this bug.

**Comment by david-barbion** [comment]
When I had this problem, I was using skype-wrapper and another script for ubuntu skype messaging indicator. That's why I saw the 2 skype icons...
What gives a "ps -ef | grep skype", in your case, when you have the problem?

**Comment by bilderbuchi** [comment]
```
    1000      1955  1857  0 11:02 ?        00:00:00 /bin/sh /usr/bin/skype-wrapper
    1000      1957  1955  0 11:02 ?        00:00:00 python /usr/share/skype-wrapper/skype-wrapper.py
    1000      2146     1  1 11:02 ?        00:00:15 skype --dbpath=/media/windata/sharedfiles/Skype-linux
    1000      2848  1957  1 11:02 ?        00:00:17 python indicator-applet-skype.py
    1000     18442 18158  0 11:22 pts/0    00:00:00 grep skype
```

I only have skype-wrapper in my startup applications.

**Comment by david-barbion** [comment]
What files do you have in /usr/share/indicators/messages/applications/ ?

**Comment by bilderbuchi** [comment]
`empathy  gwibber.indicator  thunderbird`

**Comment by bilderbuchi** [comment]
still seeing this bug, btw.

**Comment by stonerl** [comment]
I assume you have it installed from the ppa. Uninstall skype-wrapper. Remove all Startup-entries related to skype and skype wrapper. You should have no Skype Icon in the Message-Menu. Also remove the .skype-wrapper folder from your home-directory. In case the folder /usr/share/skype-wrapper still exists, remove it as well. Reinstall skype-wrapper and reboot your computer. Login and start Skype by clicking on the Skype Icon in the Message-Menu.

**Comment by bilderbuchi** [comment]
thank you. This was my mistake apparently - when I still had an icon after following your procedure, I started to dig deeper, and found a remnant of another skype messaging menu integration script I had tried out once, this was responsible for the second icon. 
Sorry for the noise, closing this.
