### ISSUE TITLE
Updating ubuntu while having the package installed botches the instalation

### ISSUE THREAD

**Issue by cronco** [sagetarian/skype-wrapper#36]
Updating from oneiric to precise today went bad when I got a message along the lines of "Error, malformed file /var/lib/dpkg/status line $x, blankline in package description of package skype-wrapper".

Again, this isn't the exact message, I've restarted a couple of times since then and managed to salvage the instalation, but that error caused the upgrade process to stop in the middle, leaving me with an unusable desktop.

**Comment by sagetarian** [comment]
I believe this was an issue with the disribution upgrade tool .. i've tested a couple times and the upgrade works fine here .. If its reproducible i'll readd it to packaging bugs

**Comment by neopostmodern** [comment]
Happend to me right now. Installation is completely broken, can't even -f.
