### ISSUE TITLE
skype-wrapper after update to Ubuntu 11.10

### ISSUE THREAD

**Issue by goblinmaks** [sagetarian/skype-wrapper#37]
skype-wrapper doesn't work on  updated ubuntu to 11.10
Step to reproduce:
1. Update Ubuntu to 11.10 from 11.04
2. Install Skype
3. Install Skype-wrapper from ppa

Actual Result:
0. Skype start correctly
1. skype-wrapper don't start correctly (See details in Log 1)
2. After start skype-wrapper from terminal, skype-wrapper icon doesn't appear in Unity panel
3. skype-wrapper widget doesn't appear in Messaging Menu

1 Log:
Starting skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
WARNING: Failed to attach skype-wrapper to Skype process
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion`g_type_from_name (name) == 0' failed
  import gobject._gobject
INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
WARNING: Failed to attach skype-wrapper to Skype process
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed

**Comment by freeq** [comment]
On ubuntu 11.10 I have the same issue

**Comment by olithered** [comment]
Did you try with the older python-skype package?

See:
  https://github.com/sagetarian/skype-wrapper/issues/4#issuecomment-2756957

**Comment by sagetarian** [comment]
can you confirm your python-skype versions please... haven't heard a reply to olithered's comment so i'll dub this closed until further notice
