### ISSUE TITLE
Support Precise in PPA

### ISSUE THREAD

**Issue by hdave** [sagetarian/skype-wrapper#38]
As an Ubuntu 12.04 beta tester, I would like to test skype-wrapper in Precise by installing from the team's PPA so that I can help ensure that this cool utility works for all Ubuntu Precise users prior to the release of 12.04 later this month.

**Comment by sagetarian** [comment]
will sort this out a.s.a.p .. thanks for the testing, always good to get support from the community

**Comment by sagetarian** [comment]
should be up and running :)
