### ISSUE TITLE
Create official ppa for easy updates in ubuntu

### ISSUE THREAD

**Issue by sagetarian** [sagetarian/skype-wrapper#4]
Need to figure out how to make a standard compliant source package .. right now im a noob at packaging on linux

**Comment by guiodic** [comment]
how you did the deb?

**Comment by sagetarian** [comment]
i used another .deb file, unpacked it, replaced it with my files .. now i know how to get my deb file to work but it has no make files or that stuff .. just debian control and readme files .. its a hack but it works

**Comment by bilderbuchi** [comment]
+1 for a PPA (and probably, bug tracking on LP would make more sense, too)

There was a 6-part series on OMGUbuntu about development for Ubuntu, starting here: http://www.omgubuntu.co.uk/2011/08/series-introduction-ubuntu-development-part-1/
Part 5 is "packaging from scratch": http://www.omgubuntu.co.uk/2011/09/20671/

Part 2 starts with packaging: http://www.omgubuntu.co.uk/2011/09/series-introduction-ubuntu-development-part-2/
Some more info in part 4 about the debian directory: http://www.omgubuntu.co.uk/2011/09/series-introduction-ubuntu-development-%e2%80%93-part-4/

All those seem to be mirrored from the Articles section here: http://developer.ubuntu.com/packaging/html/index.html

**Comment by sagetarian** [comment]
Great stuff .. thanks a ton :) we now have a PPA .. however, there's just a little bug in the current source, so don't advertise just yet :P

**Comment by bilderbuchi** [comment]
Good job, glad the info helped!

**Comment by sagetarian** [comment]
I keep getting:

Rejected:
GPG verification of /srv/launchpad.net/ppa-queue/incoming/upload-ftp-20111114-223050-000627/~shannon-netforge/skype-wrapper/ubuntu/skype-wrapper_0ubuntu5-2.7.dsc failed: Verification failed 3 times: ['No data', 'No data', 'No data']
Further error processing not possible because of a critical previous error.

**Comment by bilderbuchi** [comment]
hm, I don't know. A guess: is your gpg key setup in order? (i.e. key on the pc and on your launchpad account, etc)

**Comment by sagetarian** [comment]
yeah :) i successfully signed the *.changes file

**Comment by bilderbuchi** [comment]
hm, no idea. maybe post a question here: https://answers.launchpad.net/launchpad ?

**Comment by sagetarian** [comment]
ppa:skype-wrapper/ppa

:D

Dude you are a legend

**Comment by bilderbuchi** [comment]
you're welcome. I'll try this in the evening.

**Comment by lofidevops** [comment]
I successfully `sudo add-apt-repository ppa:shannon-netforge/skype-wrapper` which added the key from Launchpad, but when I try to reload repos and then add the package through Synaptic it complains that it isn't authenticated. Am I missing something?

**Comment by sagetarian** [comment]
yeah, seems to be an issue .. for now use <code>sudo apt-get install skype-wrapper</code>

**Comment by bilderbuchi** [comment]
I can confirm the authentication issue of kwill. Furthermore, if I install by `sudo apt-get install skype-wrapper`, it complains that 
The following packages have unmet dependencies:
 skype-wrapper : Depends: python-skype (>= 1.0.31) but it is not installable
python-skype is not in my repos. I got the skype package installed, not skype:386, if that's important (I'm on 64bit Oneiric).

Probably makes sense to put python-skype into the PPA, too.

That authentication warning can be ignored, btw, no need to install with the console. Shouldn't occur, though...

**Comment by sagetarian** [comment]
new ppa guys .. thanks to Christian Rupp!!

ppa:skype-wrapper/ppa

**Comment by lofidevops** [comment]
Unfortunately I get the missing `python-skype` issue with the new PPA as well. `python-skype` doesn't appear in my repos. Thanks for all the effort to get this going!

**Comment by sagetarian** [comment]
you'll have to install it from the debian .deb file

http://ftp.us.debian.org/debian/pool/contrib/s/skype4py/python-skype_1.0.31.0-2_all.deb

the latest version is buggy, this one = awesome

**Comment by lofidevops** [comment]
couldn't find a PPA alternative for `python-skype` (here's hoping) but I installed the deb and `skype-wrapper` installed smoothly, thanks!

**Comment by sagetarian** [comment]
awesome :) i'm super glad

**Comment by bilderbuchi** [comment]
What I meant is, is it possible to add that version of python-skype to the new PPA, so that it can be automatically installed along skype-wrapper, and people don't have to hunt it down? Also Shannon, it would reduce the effort of getting people to install the correct version.

**Comment by sagetarian** [comment]
Valid point!

https://github.com/sagetarian/skype-wrapper/issues/20
