### ISSUE TITLE
Launcher Quicklist not initialized during load up

### ISSUE THREAD

**Issue by sagetarian** [sagetarian/skype-wrapper#40]

**Comment by sagetarian** [comment]
very sporadic .. sometimes it works sometimes it doesn't .. according to debugging, it supposedly works .. my guess is its the unity launchers menu fault, but i can't blame it on something other than skype-wrapper until fully tested

**Comment by grissir** [comment]
Have this too...

**Comment by grissir** [comment]
For me the initializing always fails when I start skype-wrapper from the launcher, if I use alt+f2 it's initialized correctly every time

**Comment by grissir** [comment]
Will be fixed in v. 0.6.5
