### ISSUE TITLE
Name in ubuntu messaging menu is "Skype Wrapper" should just be "Skype"

### ISSUE THREAD

**Issue by sagetarian** [sagetarian/skype-wrapper#41]

**Comment by shvchk** [comment]
It is actually nothing wrong with version here, just launchpad version is affected (specifically /usr/share/applications/skype-wrapper.desktop — it has `Name=Skype Wrapper` in it).

Workaround: `sudo sed -i 's/Skype Wrapper/Skype!/' /usr/share/applications/skype-wrapper.desktop`
