### ISSUE TITLE
Skype-Wrapper breaky 12.04 upgrade

### ISSUE THREAD

**Issue by neopostmodern** [sagetarian/skype-wrapper#43]
I just did the 12.04 upgrad and (forgot) to remove the PPA. Result was tons of broken dependencies, tried apt-get -f install but constantly get 

dpkg: error: parsing file '/var/lib/dpkg/status' near line 162445 package 'skype-wrapper':
blank line in value of field 'Description'

tried manual uninstall and everything that came into my mind - but system stays broken; just CLI

**Comment by StanAngeloff** [comment]
@mrssheep, interesting, the upgrade tool should have auto-disabled all PPAs and I believe it's the default behaviour. Every computer I did a `update-managed -d` I had to manually edit `/etc/apt/sources.list.d` to enable PPAs again.

Do you have a lot of `*.distUpgrade` and `*.save` files in the directory above?

**Comment by neopostmodern** [comment]
Yes, `/etc/apt/sources.list.d` is full of `*.list`, `*.list.distUpgrade` and `*.list.save` files. (Meaning three for every PPA).

According to `/etc/apt/sources.list` skype-wrapper-PPA is disabled - I even enabled and purged it.

Problem is, I can't use ANY apt-get or dpkg due to the broken `/var/lib/dpkg/status` file.
I can run `skype-wrapper` through TTY (I get loads of errors though) - meaning it is still installed. Is there another way to force uninstall?

**Comment by neopostmodern** [comment]
TATAM - I solved it. The description in the status file was corrupt, VERY evil error. http://thepcspy.com/read/fixing-dpkg-status-corruption/

I dunno if this could affect other people but you should double-check that there is a `.` in that empty-line in the description.

Thanks for your advice anyway - and of course for skype-wrapper, which normally was a pleasure to use.

**Comment by StanAngeloff** [comment]
This probably means the `skype-wrapper` packages was accepted as a `.deb` and then some changes were made to `dpkg` which rendered the accepted package broken.

I am not sure what to advise, other than making a back-up of `/var/lib/dpkg/status` then editing it in a console. For reference, could you attach your `skype-wrapper` entry, mine is below:

``` deb
Package: skype-wrapper
Status: install ok installed
Priority: optional
Section: misc
Installed-Size: 171
Maintainer: Shannon Black <shannon@netforge.co.za>
Architecture: all
Version: 0ubuntu5-4.4~precise1
Depends: python-skype (>= 1.0.31), gtk2-engines-pixbuf, python (>= 2.4), python-gobject, python-indicate, python-gtk2, python-dbus, python-imaging, python-support (>= 0.90.0)
Suggests: skype
Description: Integrate Skype with Unity
 Makes Skype more native in Ubuntu by:
 * Putting skype in messaging menu, and via this
  * List all unread messages
  * Open skype and bring focus to it
  * On clicking an item remove item from skype missed chats
  * Draw attention to the Messaging Menu
  * Skype presence tied to Messaging Menu Presence (via telepathy)
 * Supply libnotify Ubuntu Desktop Notifications when
  * Users come Online or go Offline
  * Users send messages
  * Users transfer files to you or your transfers are accepted or completed by your skype contact
 * Also Disables notifications if your Online Presence is Busy / Do Not Disturb
 * Add support for unity launcher (through skype-wrapper.desktop)
  * Unread message count on unity launcher
  * Unread messages in Unity Quick List
  * File transfer progress
 * Now you can change skype-wrappers behaviour in gsettings under apps/skype-wrapper
Homepage: https://github.com/sagetarian/skype-wrapper/
```

I am not an expert, but it seems to me like you are already in a broken state so no much worse you can do if you keep proper back ups.

**Comment by neopostmodern** [comment]
```
Package: skype-wrapper
Status: install ok installed
Priority: optional
Section: Office
Installed-Size: 1.0
Maintainer: Shannon A. Black <shannon@netforge.co.za>
Architecture: all
Version: 0.5
Depends: python-skype (>= 1.0.31), gtk2-engines-pixbuf
Suggests: skype
Description: skype-wrapper
 Makes Skype more native in Ubuntu by:
 * Putting skype in messaging menu, and via this
  * List all unread messages
  * Open skype and bring focus to it
  * On clicking an item remove item from skype missed chats
  * Draw attention to the Messaging Menu
  * Skype presence tied to Messaging Menu Presence (via telepathy)
 * Supply libnotify Ubuntu Desktop Notifications when
  * Users come Online or go Offline
  * Users send messages
  * Users transfer files to you or your transfers are accepted or completed by your skype contact
 * Also Disables notifications if your Online Presence is Busy / Do Not Disturb
 * Add support for unity launcher (through skype-wrapper.desktop)
  * Unread message count on unity launcher
  * File transfer progress

 Now you can change skype-wrappers behaviour in gsettings under apps/skype-wrapper
 * Change whether you want Ubuntu Desktop Notifications:
  * During startup when users are online
  * When receiving a message
  * When users come and go offline
  * Enable or Disable Indicator Avatars
  * Enable or Disable Notification Avatar
  * Enable or Disable Notifications for incoming or outgoing file transfers
  * Enable or Disable showing file trasnfer progress in the unity launcher or choose to show only outgoing / incoming progress
```

There is an empty line before `Now you ...` without the necessary `.` - and I have copied this from the Backup; it was corrupt as well. I dunno though, why it was no problem until today.

Anyway, everything works again. (Or at least now it's not due to skype-wrapper)

**Comment by sagetarian** [comment]
thanks for sorting this out .. will push an update asap
