### ISSUE TITLE
skype wrapper crashes on startup in Ubuntu 12.04

### ISSUE THREAD

**Issue by bilderbuchi** [sagetarian/skype-wrapper#45]
Since the upgrade to precise, skype wrapper crashes on startup:

Title: indicator-applet-skype.py crashed with ISkypeAPIError in SendCommand(): Skype command timeout
Package: skype-wrapper 0ubuntu5-4.4~precise1 [origin: LP-PPA-skype-wrapper]
Uname: Linux 3.2.0-24-generic x86_64

Traceback:
 Traceback (most recent call last):
   File "indicator-applet-skype.py", line 952, in <module>
     skype = SkypeBehaviour();
   File "indicator-applet-skype.py", line 592, in **init**
     self.initOnlineUserList()
   File "indicator-applet-skype.py", line 649, in initOnlineUserList
     if self.skype.Friends:
   File "/usr/lib/pymodules/python2.7/Skype4Py/skype.py", line 1111, in _GetFriends
     return tuple([IUser(x, self) for x in self._Search('FRIENDS')])
   File "/usr/lib/pymodules/python2.7/Skype4Py/skype.py", line 421, in _Search
     return tuple(esplit(chop(self._DoCommand(com))[-1], ', '))
   File "/usr/lib/pymodules/python2.7/Skype4Py/skype.py", line 359, in _DoCommand
     self.SendCommand(command)
   File "/usr/lib/pymodules/python2.7/Skype4Py/skype.py", line 801, in SendCommand
     self._API.SendCommand(Command)
   File "/usr/lib/pymodules/python2.7/Skype4Py/API/posix_x11.py", line 405, in SendCommand
     raise ISkypeAPIError('Skype command timeout')
 ISkypeAPIError: Skype command timeout

Need any more details? I can provide an apport report.

**Comment by sagetarian** [comment]
are you using python-skype version 1.0.31 or 1.0.32 .. if so can you try the latest .deb in the github downloads section?

**Comment by sagetarian** [comment]
@bilderbuchi the issue isn't with skype-wrapper itself .. the problem is the python-skype kit which is maintained by microsoft if i'm not mistaken .. the skype connect is timing out, hardly anything skype-wrapper can do .. the only way around this i can think of is to do a python-skype version check and throw an error if its 1.0.32 .. and to ask if it can naturally reinstall a python-skype 1.0.31-2 .. thats the last working python-skype ..

**Comment by bilderbuchi** [comment]
python-skype:
  Installed: 1.0.31.0-2
skype-wrapper:
  Installed: 0ubuntu5-4.4~precise1

hm, just now it came up successfully on startup. strange. maybe an issue with network on startup? would probably make sense to retry instead of crashing, though, but I don't know if that's in your power or python-skype's?

**Comment by sagetarian** [comment]
yeah, the problem was obviously with python-skype dbus services not being ready or such ..

well actually indicator-applet-skype.py does infact run in a sandbox .. however that function is only now being sandboxed thanks to your suggestion .. what sandboxing does is it restarts the indicator-applet-skype.py if python-skype calls can't go through successfully .. hopefully it will stay sorted .. version 0.6 stable is on its way to the PPA .. let me know if any other issues arise .. really appreciate the QA'ing ;)

**Comment by bilderbuchi** [comment]
au contraire, thank _you_ for fixing things. submitting bug reports is even pleasurable if they get looked at or even fixed, not like elsewhere. :-) looking at you, ubuntu...

**Comment by sagetarian** [comment]
haha, glad i could help :) and i know exactly what you mean ;) sometimes filling out bug reports can feel like a shouting in a rock concert about a beer spill

**Comment by sagetarian** [comment]
i'm closing this until further notice :)

**Comment by bilderbuchi** [comment]
Sadly, this is still occuring on startup. skype-wrapper0ubuntu6.2.2~precise3. :-/ Please reopen.

**Comment by lredor** [comment]
Hello,

I have the same problem :(
python-skype: 1.0.31.0-2~precise1
skype-wrapper: 0ubuntu6-2.2~precise3

Traceback:
Traceback (most recent call last):
File "indicator-applet-skype.py", line 670, in checkFileTransfers 
for transfer in self.skype.FileTransfers:
File "/usr/lib/pymodules/python2.7/Skype4Py/skype.py", line 1082, in _GetFileTransfers
return tuple([IFileTransfer(x, self) for x in self._Search('FILETRANSFERS')])
File "/usr/lib/pymodules/python2.7/Skype4Py/skype.py", line 421, in _Search
return tuple(esplit(chop(self._DoCommand(com))[-1], ', '))
File "/usr/lib/pymodules/python2.7/Skype4Py/skype.py", line 359, in _DoCommand
self.SendCommand(command)
File "/usr/lib/pymodules/python2.7/Skype4Py/skype.py", line 801, in SendCommand
self._API.SendCommand(Command)
File "/usr/lib/pymodules/python2.7/Skype4Py/API/posix_x11.py", line 405, in SendCommand
raise ISkypeAPIError('Skype command timeout')
ISkypeAPIError: Skype command timeout

This problem does not occurs on startup nut just after few minutes.

Regards,

Laurent

**Comment by sagetarian** [comment]
will have to sandbox even further .. strange that it gets all the way to GetFileTransfers .. but yeah, i rate that python-skype needs some services aren't ready at start up .. sandbox all "command timeouts" and force skype-wrapper to restart until no command timeouts occur or after 5 min of trying

**Comment by bilderbuchi** [comment]
It would already be nice if the whoel thing would fail gracefully (e.g. pop up a dialog or notification saying it can't connect), and not just crash. I mean, firefox doesn't crash when it can't load a website, it just pops an error. But I guess that's out of your hand?

**Comment by gratefulfrog** [comment]
I'm having this problem as well, on Ubuntu 12.04 running on an Asus 1201N eeepc. Usually skype crashes silently on first startup, then when I re-launch, it runs ok. Hope that helps. Thanks for this great support!
Bob

**Comment by bilderbuchi** [comment]
Closing this old issue.
