### ISSUE TITLE
[Poll]: Should skype-wrapper include a full client for the version 1.0 release depending on a gsetting being set

### ISSUE THREAD

**Issue by sagetarian** [sagetarian/skype-wrapper#46]
The idea is that skype-wrapper can replace the awful non-modern QT interface of skype with a more empathy-like html5 / css / jquery customizable client if the user wants it. the option can be set in gsettings for now, until we implement a proper dialog during installation. if the gsetting says no, then skype will open as usual and skype-wrapper will not create any GUI .. this can be useful if the skype protocol ever gets open sourced, cause then we'd have an open source skype client available already. obviously, we'd need to focus on the current awful level of quality skype-wrapper seems to have at present before this though

**Comment by grissir** [comment]
+1 for this
What about skypekit, haven't heard anything about it since it was released

**Comment by bilderbuchi** [comment]
> if the skype protocol ever gets open sourced

Yeah, like this is ever gonna happen.. :-P

I'm on the fence about this. On the one hand it would be great to have, on the other hand it might be more worthwhile to integrate with an existing IM to reduce development effort.
Also, if you're already struggling to keep skype-wrapper up-to-date, I wonder if it's a smart idea to start such a big project. 
I think it would be better to focus efforts on making skype-wrapper really rock and be maintained over the releases. Currently, it crashes for me on startup in Precise (#45).

**Comment by sagetarian** [comment]
skypekit is for windows and mac users .. as far as it advertises ..there are efforts to open up the protocol, but the protocol keeps getting a flip from microsoft for there own "safety" reasons or what not

**Comment by sagetarian** [comment]
@bilderbuchi issue #45 isn't with skype-wrapper itself please check out my comment on it :) thanks .. yeah, i totally understand your issue .. as mentioned 

> obviously, we'd need to focus on the current awful level of quality skype-wrapper seems to have at present before this though

**Comment by grissir** [comment]
I'm not sure but can't we use skypekit for Embedded Devices:

"The SkypeKit for Embedded program has been created for those of you who are planning to use SkypeKit to build an embedded hardware device or a custom video application on Linux." http://developer.skype.com/public/skypekit

**Comment by sagetarian** [comment]
ah, very cool observation .. this is worth looking at in the long run

**Comment by grissir** [comment]
But I don't know if we are allowed the release the source code. I didn't find anything about it, but my head tells my that it's only for closed source apps:

"What about SkypeKit?

The SkypeKit SDK is not licensed to be used in any open-source software, such as Adium and so needs to be rewritten. SkypeKit also needs a skypekit-client program to be running in the background, so it puts us in the same boat as using the Skype API."  http://trac.adium.im/wiki/SkypeInAdium

**Comment by jnv** [comment]
I don't think it's a good idea to include a stand-alone client into `skype-wrapper`. In my opinion it's very "un-unixy" and it would make quite a mess in development: What's the bug in the wrapper? What's the bug in the client? What's the bug in the standard client?
Don't get me wrong, I like the idea of a better client, I just don't think it should be a part of skype-wrapper's development but a separate (and skype-wrapper-recommended) project. Maybe the skype-wrapper could also provide an API for other (hypothetical) clients.

**Comment by sagetarian** [comment]
@jnv good point

**Comment by felagund** [comment]
I too am definitely for ironing out skype-wrapper. I do not think that the interface of Skype is that bad anyway (and I am afraid it is probably much more bug-free than another UI would be for some time) - I am sure that even tohugh it lags behind the windows version, many human-hours were spent on QAing it.

**Comment by grissir** [comment]
Maybe it would be best to tab the windows of skype like skypetab

**Comment by sweah** [comment]
I like the idea of tabbed windows in skype-wrapper!!!!!! Would be a wonderful feature!!!!!

**Comment by Zilvador** [comment]
This sounds like a great idea!

**Comment by grissir** [comment]
I'll close the bug, because it would be to complicated to implement and with skype 4.0 we already have all conversiations in one window
