### ISSUE TITLE
[Bug] Make skype-wrapper work without Unity

### ISSUE THREAD

**Issue by ochosi** [sagetarian/skype-wrapper#47]
Currently skype-wrapper crashes (ungracefully) when launched in an environment that is not Unity. I'm using Xubuntu, but would like to have skype's messaging deposited in the messaging indicator.
It would be nice if skype-wrapper could detect it's not in Unity and try to just use the indicator then. Thanks for your work and consideration!

**Comment by sagetarian** [comment]
thanks :) can you start skype-wrapper in terminal and tell me the output

**Comment by ochosi** [comment]
thanks for your quick reply! this is the output, as you can see it gets stuck in a loop looking for "unitylauncher".

/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
skype_wrapper.log: command not found
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion`g_type_from_name (name) == 0' failed
  import gobject._gobject
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
Traceback (most recent call last):
  File "indicator-applet-skype.py", line 954, in <module>
    skype = SkypeBehaviour();
  File "indicator-applet-skype.py", line 557, in __init__
    unitylauncher.launcher.SkypeAgent = self.skype.Client
NameError: global name 'unitylauncher' is not defined
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
Traceback (most recent call last):
  File "indicator-applet-skype.py", line 954, in <module>
    skype = SkypeBehaviour();
  File "indicator-applet-skype.py", line 557, in __init__
    unitylauncher.launcher.SkypeAgent = self.skype.Client
NameError: global name 'unitylauncher' is not defined
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion`g_type_from_name (name) == 0' failed
  import gobject._gobject
Traceback (most recent call last):
  File "indicator-applet-skype.py", line 954, in <module>
    skype = SkypeBehaviour();
  File "indicator-applet-skype.py", line 557, in __init__
    unitylauncher.launcher.SkypeAgent = self.skype.Client
NameError: global name 'unitylauncher' is not defined
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
Traceback (most recent call last):
  File "indicator-applet-skype.py", line 954, in <module>
    skype = SkypeBehaviour();
  File "indicator-applet-skype.py", line 557, in __init__
    unitylauncher.launcher.SkypeAgent = self.skype.Client
NameError: global name 'unitylauncher' is not defined
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion`g_type_from_name (name) == 0' failed
  import gobject._gobject
^CTraceback (most recent call last):
  File "indicator-applet-skype.py", line 954, in <module>
    skype = SkypeBehaviour();
  File "indicator-applet-skype.py", line 557, in __init__
    unitylauncher.launcher.SkypeAgent = self.skype.Client
NameError: global name 'unitylauncher' is not defined
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr

**Comment by sagetarian** [comment]
anytime :) what do you get when you run this:

dpkg -l unity | grep "ii  unity"

or

dpkg -l unity-2d | grep "ii  unity-2d"

in terminal

**Comment by ochosi** [comment]
I get nothing (most likely because I don't have Unity or Unity-2d installed) :)

**Comment by sagetarian** [comment]
no worries .. i've sorted the issue out .. will send an update after later tonight :) will be in 0.6.2

**Comment by sagetarian** [comment]
https://github.com/downloads/sagetarian/skype-wrapper/skype-wrapper_0ubuntu6.2.0~oneiric1_all.deb

here we go .. haven't push changes to the repo yet cause i have to leave the office for the next few hours

**Comment by sagetarian** [comment]
let me know if it works :) would be great to support Xubuntu

**Comment by ochosi** [comment]
just installed/tested the package you built, but it seems it gets into yet another loop for missing wnck (libwnck-3-0, libwnck-common and libwnck22 are installed):

Starting skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
Traceback (most recent call last):
  File "indicator-applet-skype.py", line 34, in <module>
    import helpers
  File "/usr/share/skype-wrapper/helpers.py", line 35, in <module>
    import wnck
ImportError: No module named wnck
Applet closed
API crash detected
Restarting skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion`g_type_from_name (name) == 0' failed
  import gobject._gobject
Traceback (most recent call last):
  File "indicator-applet-skype.py", line 34, in <module>
    import helpers
  File "/usr/share/skype-wrapper/helpers.py", line 35, in <module>
    import wnck
ImportError: No module named wnck
Applet closed
API crash detected
Restarting skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
Traceback (most recent call last):
  File "indicator-applet-skype.py", line 34, in <module>
    import helpers
  File "/usr/share/skype-wrapper/helpers.py", line 35, in <module>
    import wnck
ImportError: No module named wnck
Applet closed
API crash detected
Restarting skype-wrapper

**Comment by ochosi** [comment]
sorry, python-wnck wasn't installed, my bad.

it seems like it's working now (notifications are there, messaging-menu integration is also there), i'll test it for a while and report back whether everything works as expected.

thanks again for your prompt support!

**Comment by grissir** [comment]
Thanks for the feedback
