### ISSUE TITLE
[Bug] All phone number contacts are notified as "online" on by one on startup

### ISSUE THREAD

**Issue by stragu** [sagetarian/skype-wrapper#48]
On startup, with Unity, there is a notification appearing for each one of the phone number contacts in the contact list, even though this kind of contacts doesn't have an online/offline status.
I know some peope don't use them, but it can get very anoying for people who store several phone numbers in there. I have 20+ phone numbers and it takes more than one minute for all the notifications to appear.

Thanks for the great work anyway! :)

**Comment by collinpeters** [comment]
+1

**Comment by sagetarian** [comment]
thanks for making me aware .. work on this

**Comment by stragu** [comment]
Thank you very much for the quick fix ! :)
