### ISSUE TITLE
Does not work if to install following instructions at OMG Ubuntu

### ISSUE THREAD

**Issue by mityukov** [sagetarian/skype-wrapper#56]
Here's the URL:
http://www.omgubuntu.co.uk/2012/05/skype-wrapper-adds-call-actions-notification-fixes-ubuntu-12-04-support/

Installed this wrapper in Ubuntu 12.04, following these instructions. the resukt is that it doesn't work. Looks there is missing dependency: ImportError: No module named wnck
## Console repeats this piece of text until clicking Ctrl+C:

Restarting skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
Traceback (most recent call last):
  File "indicator-applet-skype.py", line 34, in <module>
    import helpers
  File "/usr/share/skype-wrapper/helpers.py", line 35, in <module>
    import wnck
ImportError: No module named wnck
Applet closed

**Comment by mityukov** [comment]
installation of "python-wnck" solved the issue.

**Comment by sagetarian** [comment]
thanks for this .. adding it to the list of dependencies a.s.a.p
