### ISSUE TITLE
Missing python-wnck dependency?

### ISSUE THREAD

**Issue by purple52** [sagetarian/skype-wrapper#57]
I just did an upgrade on 12.04 and skype-wrapper would no longer start, repeating the error belong. Installing the python-wnck package fixed the problem.

/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
Traceback (most recent call last):
  File "indicator-applet-skype.py", line 34, in <module>
    import helpers
  File "/usr/share/skype-wrapper/helpers.py", line 35, in <module>
    import wnck
ImportError: No module named wnck
Applet closed
API crash detected

**Comment by sagetarian** [comment]
weird .. assumed python-wnck would be installed in the default ubuntu .. can you check if python-wnck is in the default repository? i.e can you install it from synaptic? otherwise i'll have to package it in the PPA

**Comment by purple52** [comment]
Yes, it is available in the default repo:
http://packages.ubuntu.com/search?keywords=python-wnck

Running "sudo apt-get install python-wnck" resolved the problem, so adding it as a dependency should work just fine.

**Comment by sagetarian** [comment]
awesome :) will push to PPA asap ..
