### ISSUE TITLE
[BUG]: skype-wrapper in autostart opens skype repeatedly

### ISSUE THREAD

**Issue by sagetarian** [sagetarian/skype-wrapper#6]
Максим Кузнецов:

When i'm putting skype-wrapper in autostart, it starts skype several times and doesn't appear in indicator applet. When i'm killing skype, skype-wrapper starts it automatically, closes window and appears in indicator applet. The same happens when i'm killing both skype-wrapper and skype and starting skype-wrapper: skype starts once, window closes, skype-wrapper appears in indicator applet correctly.

**Comment by sagetarian** [comment]
The latest version (0.5.2.8 at the time) should do the trick .. its in the downloads section .. feel free to reopen this bug if it continues :)

**Comment by bilderbuchi** [comment]
This is or something similar is happening for me in 0ubuntu5-2.10 from the PPA.
While I only get one skype on autostarting skype-wrapper, it's impossible to kill it. 
If I ctrl-q skype, it quits, only to start again after a couple seconds.
If I kill skype-wrapper in the system monitor, then quit skype, it starts again after a couple seconds.
Even if I forcibly kill skype itself (when skype-wrapper is already dead), it comes back from the dead. 

Maybe relevant: I've been running skype-wrapper for ~20mins now, but the API permission dialog has not yet appeared (so no ubuntu-notifications appear, yet). Also, I use the custom command option setting you provided. My profile loads correctly, so it seems to work as intended.

zombie skype, help! burn it with fire! Should I file a separate issue.

**Comment by bilderbuchi** [comment]
Ok, so it seems that after I killed both skype and skype-wrapper and quickly started skype-wrapper with Alt-F2, the popup appeared, I confirmed, and now Skype stays down when quit.
Still no/spotty indicators, but I'll open a separate issue for that.

**Comment by bilderbuchi** [comment]
Huh, seems I spoke too soon. Now it's back again to endlessly resurrecting skype. :-(

**Comment by sagetarian** [comment]
kill indicator-skype not skype-wrapper :) that is the way to force it to quit if the bug is in indicator-skype .. skype-wrapper shouldnt ressurect itself though :/ but it does ressurect indicator-skype .. also its resurrecting indicator-skype because indicator-skype is failing

**Comment by sagetarian** [comment]
what python-skype are you running?

**Comment by bilderbuchi** [comment]
OK If I kill indicator-skype, skype stays down.
Clarification: a killed skype-wrapper doesn't resurrect itself, but skype (at least that's what it looked like before - I was not aware of indicator-skype)
python-skype: 1.0.31.0-2

**Comment by sagetarian** [comment]
yeah .. currently this is how it works

skype-wrapper checks if indicator-skype is running already, if so bring focus to it and quit (no need for skype-wrapper)..
else start indicator-skype .. indicator-skype checks if skype is running .. if it is attempt to attach to it.. if it fails to attach, then reload indicator-skype ..

now with yours, the only reason i see skype being restarted is if it fails to attach to skype .. are you running those extra cmd params ?
but then you wouldnt see it in UMM

**Comment by bilderbuchi** [comment]
Is this a description of what happens when I quit skype?

If I start skype-wrapper in terminal, the output is
~$ skype-wrapper 
Starting skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
INFO: Initializing Skype API
Corrupt JPEG data: 291 extraneous bytes before marker 0xd9

then as soon as i quit skype

INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
INFO: Initializing Skype API
Corrupt JPEG data: 291 extraneous bytes before marker 0xd9

Yes I'm running those extra cmd parameters - " --dbpath=<path-to-profile>" to be precise. mind the space in the beginning, should I delete that?

**Comment by sagetarian** [comment]
try running it without the command parameters .. maybe the python skype API is a bit retarded .. here's the new 

https://github.com/downloads/sagetarian/skype-wrapper/skype-wrapper_0ubuntu5-2.12_all.deb

enable debugging in deconf-editor and you should get a log file in ~/.skype-wrapper/log.txt

**Comment by bilderbuchi** [comment]
will try this tomorrow, I have to relocate my profile first, but i gotta go now. thanks for now!

new deb file: On install with gdebi or software center, I get
Failed to open the software package
The package might be corrupted or you are not allowed to open the file. Check the permissions of the file.

Permissions are ok, I checked.

**Comment by sagetarian** [comment]
I managed to replicate the bug about skype reopening alot after autostarting .. this is how i did it:
1. Logged in
2. Skype tried to connect but no internet connection yet so failed
3. I closed skype
   4 alot of skype windows started opening

Will work on a fix soon

**Comment by sagetarian** [comment]
should be fixed in 0.5.3.5

Please confirm

**Comment by sagetarian** [comment]
closing this issue until further notice
