### ISSUE TITLE
[Bug] Make skype-wrapper work without Unity (again)

### ISSUE THREAD

**Issue by alex-ball** [sagetarian/skype-wrapper#63]
I'm using (freshly installed) Xubuntu 12.04 with the package version 0ubuntu6.2.2~precise3 and Skype version 2.2.0.35-0precise3. The problem has reappeared whereby skype-wrapper goes off in a loop looking for Unity, which I don't have being on Xubuntu (but I would nevertheless like to integrate Skype into the messaging indicator).

I give you the terminal output of the first cycle of this loop:

`Starting skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
INFO: Initializing Skype API
INFO: Starting Skype process
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
WARNING: Failed to attach skype-wrapper to Skype process
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
INFO: Attached complete
Traceback (most recent call last):
  File "indicator-applet-skype.py", line 957, in <module>
    skype = SkypeBehaviour();
  File "indicator-applet-skype.py", line 560, in __init__
    unitylauncher.launcher.SkypeAgent = self.skype.Client
NameError: global name 'unitylauncher' is not defined
Applet closed
API crash detected`

Many thanks if you can sort this out!

**Comment by grissir** [comment]
We already know about this, but I had no time to fix this yet

**Comment by grissir** [comment]
We have plans to support non unity enviroments in version 0.6.6

**Comment by grissir** [comment]
even better it will be included in version 6.4.2 which will be published on tuesday
