### ISSUE TITLE
Indicator drop-down menu flickers once every time it is clicked

### ISSUE THREAD

**Issue by stragu** [sagetarian/skype-wrapper#64]
Hi there! Thanks for the great work for this plugin.

An issue I noticed is that, when using the wrapper and clicking on the green Skype indicator icon in the top panel, the drop down menu flickers once (not a tiny flicker, more like the menu disappearing for a short amount of time). This happens every time it is clicked.

Note that I uninstalled the messaging menu on my Ubuntu 12.04.

Anyone else witnessing this?

Cheers, and again, thanks for the great work!

**Comment by grissir** [comment]
Thank you for the report, but this isn't a bug of skype-wrapper. It also happens when skype-wrapper is not installed. I think it is a bug of sni-qt. The bug-tracker is  here https://bugs.launchpad.net/ubuntu/+source/sni-qt .

**Comment by stragu** [comment]
Thank you for that quick response, and sorry about the mistake!
Cheers!
