### ISSUE TITLE
Error in MeMenu Ubuntu 12.04

### ISSUE THREAD

**Issue by acutbal** [sagetarian/skype-wrapper#71]
Hello!!

In Ubuntu 12.04 64 bits and the last version of Skype-wrapper when I close without exiting my account I get two "skypes" in the MeMenu. However it doesn't succes if I only minimize.

http://ubuntuone.com/5uaHiTZzJV5y04aFzcqwDI

In the other hand, the previous bug with two launchers in the Unity bar is solved.

Best regards.

**Comment by stonerl** [comment]
Could you please open the bugreport on launchpad: https://bugs.launchpad.net/skype-wrapper
and tell us which version you use.
