### ISSUE TITLE
Skype wrapper keeps showing up skype window when skype is started through skype-wrapper icon

### ISSUE THREAD

**Issue by marcin-antas** [sagetarian/skype-wrapper#73]
I have added skype-wrapper icon to my unity luncher and when I start skype by clicking on the skype-wrapper icon the skype-wrapper keeps showing up the skype window and doesn't stop but when I start skype by clicking on original skype icon, then the skype-wrapper works fine and the skype window doesn't keep  on showing up all the time.

I have enabled logs for skype-wrapper but they didn't tell me much. 
I am using Ubuntu 12.04.1 LTS with Unity 5.14.0.

**Comment by Desiderata** [comment]
I have the same problem.
Ubuntu 12.04 x64.

**Comment by sagetarian** [comment]
hey :) the community moved the repo to launchpad .. here's the bug 

https://bugs.launchpad.net/skype-wrapper/+bug/1052458

we're working on a fix

**Comment by Desiderata** [comment]
I find solution:

Error in file skype-wrapper.py in line 60 : 'if end - start < 5:'
if end - start < 5:
    print "API crash detected"
    print "Restarting skype-wrapper"
    start_skype()

Need change it to 'if end - start < 4:'
if end - start < 4:
    print "API crash detected"
    print "Restarting skype-wrapper"
    start_skype()

**Comment by marcin-antas** [comment]
Hmm, I've changed the python code as you wrote (i think you made a mistake it's line 82 not 60) but it didn't work, it still behaves the same.

**Comment by Desiderata** [comment]
From launchpad.net:
"If in Skype-wrapper settings Autostart is enabled - you DON'T need to start skype-wrapper, instead run skype and skype-wrapper will works fine!"

Maybe it will help you.

Or

Try to change 4 to 1.

**Comment by marcin-antas** [comment]
I know about this workaround (start skype than skype-wrapper) also I've seen on lunchpad that it was fixed recently, so I think I'll wait for an update.

Thanks for your help.

**Comment by sagetarian** [comment]
if you want to fix it right now instead of waiting .. change the launcher.py line that says:

<code>if bus.name_has_owner('com.Skype.API'):</code>

to

<code>if bus.name_has_owner('com.Skype.API') and not bus.name_has_owner('org.skypewrapper.skypewrapper'):</code>

**Comment by marcin-antas** [comment]
I found python scripts for skype wrapper in /usr/share/skype-wrapper and I changed the launcher.py file as you have written but it didn't help... am I doing something wrong ?

**Comment by sagetarian** [comment]
after reboot it should work :) the problem is launcher.py runs in the background .. so any changes you make to it will not have any effect until you reboot or end process it in system monitor .. but i have to push the code that names it for you to find it in system monitor :)

**Comment by marcin-antas** [comment]
Thanks a lot for your reply, the reboot did the trick :) now the skype wrapper works fine :)
