### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ghost** [sagetarian/skype-wrapper#74]
I get this error when starting skype-wrapper

/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
Starting skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion`g_type_from_name (name) == 0' failed
  import gobject._gobject
INFO: Initializing Skype API
INFO: Starting Skype process
Traceback (most recent call last):
  File "indicator-applet-skype.py", line 1087, in <module>
    skype = SkypeBehaviour();
  File "indicator-applet-skype.py", line 530, in __init__
    subprocess.Popen(shlex.split("skype"))
  File "/usr/lib/python2.7/subprocess.py", line 679, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Applet closed
API crash detected
Restarting skype-wrapper

Version: 0ubuntu6.5.2~precise4 - Skype-wrapper
Version: 1.0.32.0-1~precise1 - Python-skype
Version: 3.2.0-31-generic-pae - Ubuntu

**Comment by grissir** [comment]
Can you please report it here https://launchpad.net/skype-wrapper no one is maintaining GitHup anymore
