### ISSUE TITLE
Cannot turn off "User went online" notifications

### ISSUE THREAD

**Issue by lefterav** [sagetarian/skype-wrapper#75]
I am trying to stop python-wrapper from giving me all possible notifications. Particularly, I want to stop "User went online" and "User went offline" messages. They are to many and they distract me as I work.

I tried to change that from the original skype options / notifications, but skype-wrapper ignores the setting and keeps displaying them.

**Comment by grissir** [comment]
skype wrapper has it's own settings dialog which can be found by searching the dash it is named Skype-wrapper settings

**Comment by lefterav** [comment]
The settings panel does not actually start if you type skype-wrapper-settings on drush. In fact one has to look for s-wrapper-settings. I found tha by chance. I have to comment that this settings panel is totally hidden, and one should actually find a better way to offer it to the user.
