### ISSUE TITLE
messages don't appear at the messaging menu

### ISSUE THREAD

**Issue by copocaneta** [sagetarian/skype-wrapper#77]
Hello there,

First of all thanks for your time on this project, this is really good.

I am using Ubuntu 12.04 64 bit and Skype 4.1.0.20.

Installed Skype through USC.

After installing skype-wrapper and allowing the Skype API Authrorization request, whenever I receive a message:

1 -  The messages won't show up at the messaging menu

2 - I don't receive the notification at the top right, instead I receive that tiny default skype notification at the bottom right

Could you please help?

Let me know if you need any logs or something.

Thanks in advance.

**Comment by copocaneta** [comment]
$ skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
Starting skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion`g_type_from_name (name) == 0' failed
  import gobject._gobject
INFO: Initializing Skype API
INFO: Starting Skype process
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
INFO: Attached complete
INFO: Initializing online status for users
INFO: We are offline
INFO: We are offline
INFO: We are offline
INFO: We are offline

**Comment by haeckle** [comment]
same problem here and I also got the same configuration (Ubuntu 12.04 64bit and Skype from Ubuntu Software Center).

**Comment by grissir** [comment]
Hi we moved too launchpad... https://launchpad.net/skype-wrapper 
I know that the current implementation of skype wrapper has some flawns hopefully I will find time to solve them before 13.10
