### ISSUE TITLE
High CPU usage of skype-wrapper

### ISSUE THREAD

**Issue by myshov** [sagetarian/skype-wrapper#80]
Skype-wrapper (installed from ppa) causes high cpu usage (more then 50% on Core 2 Duo T5870). Loading on CPU without wrapper is less then 10%.

OS: Ubuntu 13.04 (32 bit)
Skype: 4.2.0.11

skype-wrapper log: http://ubuntuone.com/4Y504Ez3KpjjdT6Wfn8WwO

**Comment by grissir** [comment]
known... please don't report bugs for ubuntu versions above 12.10 as we haven't done anything to support the new api. 
Also please report bugs on launchpad
